config/routes.rb
Rails.application.routes.draw do
  resources :shopping_list, only: [ :new, :create, :show ]
  resources :recipes do
    resources :recipe_foods
  end
  resources :inventories do
    resources :inventory_foods
  end
  resources :foods
  resources :dashboard, only: [ :index ]
  devise_for :users
  get "up" => "rails/health#show", as: :rails_health_check
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :shopping_list_items, dependent: :destroy
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods
  has_many :inventory_foods, dependent: :destroy
  has_many :inventories, through: :inventory_foods
  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, presence: true
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user
  has_many :inventory_foods
  has_many :shopping_lists, dependent: :destroy
  has_many :foods, through: :inventory_foods
end

app/models/inventory_food.rb
class InventoryFood < ApplicationRecord
  belongs_to :inventory
  belongs_to :food
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :shopping_lists, dependent: :destroy
  has_many :foods, through: :recipe_foods

  def preparation_duration
    return "" if preparation_time.nil?
    "%02d:%02d" % [ preparation_time / 60, preparation_time % 60 ]
  end

  def preparation_duration=(value)
    if value =~ /\A\d{1,2}:\d{2}\z/
      h, m = value.split(":").map(&:to_i)
      self.preparation_time = h * 60 + m
    end
  end

  def cooking_duration
    return "" if cooking_time.nil?
    "%02d:%02d" % [ cooking_time / 60, cooking_time % 60 ]
  end

  def cooking_duration=(value)
    if value =~ /\A\d{1,2}:\d{2}\z/
      h, m = value.split(":").map(&:to_i)
      self.cooking_time = h * 60 + m
    end
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food
  belongs_to :recipe
end

app/models/shopping_list.rb
class ShoppingList < ApplicationRecord
  belongs_to :recipe
  belongs_to :inventory
  belongs_to :user
  has_many :shopping_list_items, dependent: :destroy
end

app/models/shopping_list_item.rb
class ShoppingListItem < ApplicationRecord
  belongs_to :shopping_list
  belongs_to :food
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :recipes
  has_many :inventories
  has_many :shopping_lists
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  layout "admin"
  before_action :authenticate_user!
  before_action :set_food, only: [ :destroy ]

  def index
    @foods=Food.all
  end

  def new
  end

  def create
    @food = Food.create(food_params)
    if @food.save
      respond_to do |format|
        format.html { redirect_to foods_url, notice: "Food added" }
      end
    else
      respond_to do |format|
        format.html { redirect_to foods_url, alert: @food.errors.full_messages[0] }
      end
    end
  end

  def destroy
    if @food.destroy
      respond_to do |format|
        format.html { redirect_to foods_url, notice: "Food deleted!" }
      end
    else
      respond_to do |format|
        format.html { redirect_to foods_url, alert: @food.errors.full_messages[0] }
      end
    end
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price)
  end

  def set_food
    @food = Food.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  layout "admin"
  before_action :authenticate_user!
  before_action :set_inventory, only: [ :show, :destroy ]
  def index
    @inventories=Inventory.all
  end

  def new
  end

  def show
  end

  def create
    @inventory = current_user.inventories.create(inventory_params)
    if @inventory.save
      respond_to do |format|
        format.html { redirect_to inventories_url, notice: "Inventory added" }
      end
    else
      respond_to do |format|
        format.html { redirect_to inventories_url, alert: @inventory.errors.full_messages }
      end
    end
  end

  def destroy
    if @inventory.destroy
      respond_to do |format|
        format.html { redirect_to inventories_url, notice: "Inventory deleted" }
      end
    else
      respond_to do |format|
        format.html { redirect_to inventories_url, alert: @inventory.errors.full_messages[0] }
      end
    end
  end

  private
  def inventory_params
    params.require(:inventory).permit(:name, :description)
  end

  def set_inventory
    @inventory= Inventory.find(params[:id])
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  layout "admin"
  before_action :set_recipe, only: [ :destroy, :show ]

  def index
    @recipes = Recipe.all
  end

  def show
  end

  def new
  end

  def create
    @recipe = current_user.recipes.create(recipe_params)
    if @recipe.save
      respond_to do |format|
        format.html { redirect_to recipes_url, notice: "Recipe added!" }
      end
    else
    respond_to do |format|
        format.html { redirect_to recipes_url, alert: @recipe.errors.full_messages[0] }
      end
    end
  end

  def destroy
    if @recipe.destroy
      respond_to do |format|
        format.html { redirect_to recipes_url, notice: "Recipe deleted!" }
      end
    else
      respond_to do |format|
        format.html { redirect_to recipes_url, alert: @recipe.errors.full_messages[0] }
      end
    end
  end

  private
  def recipe_params
    params.require(:recipe).permit(:name, :description, :preparation_duration, :cooking_duration, :public)
  end
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/inventory_foods_helper.rb
module InventoryFoodsHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shopping_list_helper.rb
module ShoppingListHelper
end

app/views/inventories/index.html.erb
<div class="flex flex-col w-full text-gray-200">
  <div class="flex items-center px-10 <%= @inventories.size > 0 ? "justify-end" : "justify-between" %> my-4">
    <% if @inventories.size < 1 %>
      <p class="font-bold text-xl text-yellow-300">No inventory items added yet!</p>
    <%end%>
    <%= button_to "Add Inventory", new_inventory_path, method: :get, data: {turbo: true, turbo_frame: :modal},
    class:"bg-blue-500 p-2 rounded-md cursor-pointer" %>
  </div>
  <div class="flex flex-col justify-center items-center">
    <% @inventories.each do |inventory|%>
      <div class="flex flex-col md:flex-row text-xs sm:text-base overflow-x-hidden gap-10 border border-gray-400 w-[80%] shadow-md m-4 p-5 px-10 rounded-md">
        <div class="flex flex-col items-center justify-center gap-5">
          <p class="font-semibold text-sm md:text-xl text-blue-300 underline">
            <%=link_to inventory.name, inventory_path(inventory) %>
          </p>
          <%=button_to "REMOVE", inventory_path(inventory), method: :delete, class:"text-blue-400 uppercase cursor-pointer"%>
        </div>
        <div class="">
          <p>
            <%= inventory.description%>
          <p>
        </div>
      </div>
    <%end%>
  </div>
</div>

app/views/inventories/new.html.erb
<%= turbo_frame_tag :modal do %>
  <div class="fixed inset-0 bg-black/80"></div>
  <div class="fixed inset-0 bg-transparent flex items-center justify-center">
    <div class="relative flex items-center justify-center w-96 z-50 bg-gray-400 p-4 rounded-md">
      <%= form_with model: Inventory.new, data: {turbo: false} do |f|%>
        <div class="mb-4">
          <%= f.label :name, class:"block mb-2 text-gray-950" %>
          <%= f.text_field :name,
            autofocus: false,
            autocomplete: "name",
            class: "w-full px-3 py-2 border text-gray-100 rounded-lg bg-gray-600 outline-none"
          %>
        </div>
        <div class="mb-4">
          <%= f.label :description, class:"block mb-2 text-gray-950" %>
          <%= f.text_field :description,
            autofocus: true,
            autocomplete: "description",
            class: "w-full px-3 py-2 border text-gray-100 rounded-lg bg-gray-600 outline-none"
          %>
        </div>
        <div class="flex items-center justify-center mb-2 my-2">
          <%= f.submit "Create",
            class:"bg-orange-500 hover:bg-orange-600 text-gray-200 font-semibold lg:text-xl p-2 rounded-md cursor-pointer w-[70%]",
            data: {turbo_frame: "_top"}
            %>
        </div>
        <div class="absolute top-2 right-2">
          <%=link_to inventories_path do %>
            <%= inline_svg_tag("close.svg", class:"text-gray-800 size-8")%>
          <%end%>
        </div>
      <%end%>
    </div>
  <div>
<%end%>

app/views/inventories/show.html.erb
<div class="flex flex-col text-xs md:text-base items-center mt-10 text-gray-200 w-full">
  <p class="font-semibold text-xl">
    <%=@inventory.name%>
  </p>
  <div class="flex justify-end md:w-[80%]">
    <%= link_to "Add Food", new_inventory_inventory_food_path(@inventory), data: {turbo: true, turbo_frame: :modal}, class:"cursor-pointer bg-blue-500 rounded-md p-1 hover:bg-blue-400" %>
  </div>
  <div class="border-b-2 border-blue-400 my-2 md:w-[80%]"></div>
  <div class="w-full md:w-[80%] p-2 bg-gray-600 rounded-md">
    <table class="w-full">
      <thead>
        <tr class="text-left capitalize md:uppercase border-b border-blue-500">
          <th class="sm:px-4 sm:py-3">Food</th>
          <th class="sm:px-4 sm:py-3">Quantity</th>
          <th class="sm:px-4 sm:py-3">Actions</th>
        </tr>
      </thead>
      <tbody>
        <%@inventory.inventory_foods.each do |inventory_food|%>
        <tr class="my-1">
          <td class="px-4 py-3"><%=inventory_food.food.name%></td>
          <td class="px-4 py-3">
            <%=inventory_food.quantity%>
            <span class="italic">
              <%=inventory_food.food.measurement_unit%>
            </span>
          </td>
          <td class="px-4 py-3">
            <%=button_to "Delete", inventory_inventory_food_path(@inventory, inventory_food), method: :delete, class:"text-blue-400 underline cursor-pointer"%>
          </td>
        </tr>
        <%end%>
      </tbody>
    </table>
  </div>
</div>