config/routes.rb
Rails.application.routes.draw do
  resources :shopping_list, only: [ :new, :create, :show ]
  resources :recipes do
    resources :recipe_foods
  end
  resources :inventories do
    resources :inventory_foods
  end
  resources :foods
  resources :dashboard, only: [ :index ]
  devise_for :users
  get "up" => "rails/health#show", as: :rails_health_check
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :shopping_list_items, dependent: :destroy
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods
  has_many :inventory_foods, dependent: :destroy
  has_many :inventories, through: :inventory_foods
  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, presence: true
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user
  has_many :inventory_foods
  has_many :shopping_lists, dependent: :destroy
  has_many :foods, through: :inventory_foods
end

app/models/inventory_food.rb
class InventoryFood < ApplicationRecord
  belongs_to :inventory
  belongs_to :food
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :shopping_lists, dependent: :destroy
  has_many :foods, through: :recipe_foods

  def preparation_duration
    return "" if preparation_time.nil?
    "%02d:%02d" % [ preparation_time / 60, preparation_time % 60 ]
  end

  def preparation_duration=(value)
    if value =~ /\A\d{1,2}:\d{2}\z/
      h, m = value.split(":").map(&:to_i)
      self.preparation_time = h * 60 + m
    end
  end

  def cooking_duration
    return "" if cooking_time.nil?
    "%02d:%02d" % [ cooking_time / 60, cooking_time % 60 ]
  end

  def cooking_duration=(value)
    if value =~ /\A\d{1,2}:\d{2}\z/
      h, m = value.split(":").map(&:to_i)
      self.cooking_time = h * 60 + m
    end
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food
  belongs_to :recipe
end

app/models/shopping_list.rb
class ShoppingList < ApplicationRecord
  belongs_to :recipe
  belongs_to :inventory
  belongs_to :user
  has_many :shopping_list_items, dependent: :destroy
end

app/models/shopping_list_item.rb
class ShoppingListItem < ApplicationRecord
  belongs_to :shopping_list
  belongs_to :food
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :recipes
  has_many :inventories
  has_many :shopping_lists
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  layout "admin"
  before_action :authenticate_user!
  before_action :set_food, only: [ :destroy ]

  def index
    @foods=Food.all
  end

  def new
  end

  def create
    @food = Food.create(food_params)
    if @food.save
      respond_to do |format|
        format.html { redirect_to foods_url, notice: "Food added" }
      end
    else
      respond_to do |format|
        format.html { redirect_to foods_url, alert: @food.errors.full_messages[0] }
      end
    end
  end

  def destroy
    if @food.destroy
      respond_to do |format|
        format.html { redirect_to foods_url, notice: "Food deleted!" }
      end
    else
      respond_to do |format|
        format.html { redirect_to foods_url, alert: @food.errors.full_messages[0] }
      end
    end
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price)
  end

  def set_food
    @food = Food.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  layout "admin"
  before_action :set_recipe, only: [ :destroy, :show ]

  def index
    @recipes = Recipe.all
  end

  def show
  end

  def new
  end

  def create
    @recipe = current_user.recipes.create(recipe_params)
    if @recipe.save
      respond_to do |format|
        format.html { redirect_to recipes_url, notice: "Recipe added!" }
      end
    else
    respond_to do |format|
        format.html { redirect_to recipes_url, alert: @recipe.errors.full_messages[0] }
      end
    end
  end

  def destroy
    if @recipe.destroy
      respond_to do |format|
        format.html { redirect_to recipes_url, notice: "Recipe deleted!" }
      end
    else
      respond_to do |format|
        format.html { redirect_to recipes_url, alert: @recipe.errors.full_messages[0] }
      end
    end
  end

  private
  def recipe_params
    params.require(:recipe).permit(:name, :description, :preparation_duration, :cooking_duration, :public)
  end
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end
end

app/controllers/shopping_list_controller.rb
class ShoppingListController < ApplicationController
  before_action :authenticate_user!
  layout "admin"

  def index
  end

  def new
    @recipe = Recipe.find(params[:recipe_id])
    @inventories = current_user.inventories
    @shopping_list = ShoppingList.new
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @inventory = Inventory.find(params[:inventory_id])

    shopping_list = current_user.shopping_lists.create!(recipe: @recipe, inventory: @inventory)

    inventory_food_quantities = @inventory.inventory_foods.each_with_object({}) do |inv_food, hash|
      hash[inv_food.food_id] = inv_food.quantity
    end

    @recipe.recipe_foods.includes(:food).each do |recipe_food|
      required_qty = recipe_food.quantity
      available_qty = inventory_food_quantities[recipe_food.food_id] || 0

      if available_qty < required_qty
        needed_qty = required_qty - available_qty
        ShoppingListItem.create!(
          shopping_list: shopping_list,
          food: recipe_food.food,
          needed: needed_qty,
          unit_price: recipe_food.food.price,
          total_value: needed_qty * recipe_food.food.price
        )
      end
    end

    redirect_to shopping_list_path(shopping_list)
  end

  def show
    @shopping_list = current_user.shopping_lists.includes(shopping_list_items: :food).find(params[:id])
    @missing_items = @shopping_list.shopping_list_items.includes(:food)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/inventory_foods_helper.rb
module InventoryFoodsHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shopping_list_helper.rb
module ShoppingListHelper
end

app/views/shopping_list/index.html.erb
<div>
  <h1 class="font-bold text-4xl">ShoppingList#index</h1>
  <p>Find me in app/views/shopping_list/index.html.erb</p>
</div>

app/views/shopping_list/new.html.erb
<%= turbo_frame_tag :modal do %>
  <div class="fixed inset-0 bg-black/80"></div>
  <div class="fixed inset-0 bg-transparent flex items-center justify-center">
    <div class="relative flex flex-col items-center justify-center w-96 z-50 bg-gray-400 p-4 rounded-md">
      <h2 class="font-bold">Generate Shopping List</h2>
      <div class="w-full flex items-start my-10">
        <p>Choose an inventory to use</p>
      </div>
      <%= form_with url: shopping_list_index_path, method: :post, local: true do |f|%>
      <%= hidden_field_tag :recipe_id, @recipe.id%>
      <div class="flex items-center justify-between gap-10">
        <div class="mb-4">
          <%= f.label :inventory_id, "Select inventory", class:"block mb-2 text-gray-950" %>
          <%= f.collection_select :inventory_id, @inventories, :id, :name %>
        </div>
        <div class="flex items-center justify-center mb-2 my-2">
          <%= f.submit "Generate",
            class:"bg-orange-500 hover:bg-orange-600 text-gray-200 font-semibold lg:text-xl p-2 rounded-md cursor-pointer w-full",
            data: {turbo_frame: "_top"}
            %>
        </div>
      </div>
        <div class="absolute top-2 right-2">
          <%=link_to recipes_path do %>
            <%= inline_svg_tag("close.svg", class:"text-gray-800 size-8")%>
          <%end%>
        </div>
      <%end%>
    </div>
  <div>
<%end%>

app/views/shopping_list/show.html.erb
<div class="flex flex-col items-center text-xs md:text-base justify-center text-gray-200 p-2 w-full">
  <p class="font-bold text-2xl my-10">Your Shopping List</p>
  <div class="flex gap-5">
    <p>Amount of food items to buy: <%=@missing_items.size%></p>
    <p>Total value of food needed: <%= number_to_currency(@missing_items.sum { |item| item[:total_value].to_f })%></p>
  </div>
  <div class="border-b-2 border-gray-950 my-2 w-full md:w-[80%]"></div>
    <div class="bg-gray-600 rounded-md px-2 w-full md:w-[80%]">
      <table class="w-full">
        <thead>
          <tr class="text-left capitalize md:uppercase border-b border-blue-500">
            <th class="sm:px-4 sm:py-3">Food</th>
            <th class="sm:px-4 sm:py-3">Quantity</th>
            <th class="sm:px-4 sm:py-3">Value</th>
          </tr>
        </thead>
        <tbody>
          <% @missing_items.each do |item| %>
            <tr>
              <td class="px-4 py-3"><%=  item.food.name %></td>
              <td class="px-4 py-3"><%= item[:needed] %></td>
              <td class="px-4 py-3"><%= number_to_currency(item[:total_value]) %></td>      
            <tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>