config/routes.rb
Rails.application.routes.draw do
  resources :shopping_list, only: [ :new, :create, :show ]
  resources :recipes do
    resources :recipe_foods
  end
  resources :inventories do
    resources :inventory_foods
  end
  resources :foods
  resources :dashboard, only: [ :index ]
  devise_for :users
  get "up" => "rails/health#show", as: :rails_health_check
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :shopping_list_items, dependent: :destroy
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods
  has_many :inventory_foods, dependent: :destroy
  has_many :inventories, through: :inventory_foods
  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, presence: true
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user
  has_many :inventory_foods
  has_many :shopping_lists, dependent: :destroy
  has_many :foods, through: :inventory_foods
end

app/models/inventory_food.rb
class InventoryFood < ApplicationRecord
  belongs_to :inventory
  belongs_to :food
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :shopping_lists, dependent: :destroy
  has_many :foods, through: :recipe_foods

  def preparation_duration
    return "" if preparation_time.nil?
    "%02d:%02d" % [ preparation_time / 60, preparation_time % 60 ]
  end

  def preparation_duration=(value)
    if value =~ /\A\d{1,2}:\d{2}\z/
      h, m = value.split(":").map(&:to_i)
      self.preparation_time = h * 60 + m
    end
  end

  def cooking_duration
    return "" if cooking_time.nil?
    "%02d:%02d" % [ cooking_time / 60, cooking_time % 60 ]
  end

  def cooking_duration=(value)
    if value =~ /\A\d{1,2}:\d{2}\z/
      h, m = value.split(":").map(&:to_i)
      self.cooking_time = h * 60 + m
    end
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food
  belongs_to :recipe
end

app/models/shopping_list.rb
class ShoppingList < ApplicationRecord
  belongs_to :recipe
  belongs_to :inventory
  belongs_to :user
  has_many :shopping_list_items, dependent: :destroy
end

app/models/shopping_list_item.rb
class ShoppingListItem < ApplicationRecord
  belongs_to :shopping_list
  belongs_to :food
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :recipes
  has_many :inventories
  has_many :shopping_lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  layout "admin"
  before_action :authenticate_user!
  before_action :set_food, only: [ :destroy ]

  def index
    @foods=Food.all
  end

  def new
  end

  def create
    @food = Food.create(food_params)
    if @food.save
      respond_to do |format|
        format.html { redirect_to foods_url, notice: "Food added" }
      end
    else
      respond_to do |format|
        format.html { redirect_to foods_url, alert: @food.errors.full_messages[0] }
      end
    end
  end

  def destroy
    if @food.destroy
      respond_to do |format|
        format.html { redirect_to foods_url, notice: "Food deleted!" }
      end
    else
      respond_to do |format|
        format.html { redirect_to foods_url, alert: @food.errors.full_messages[0] }
      end
    end
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price)
  end

  def set_food
    @food = Food.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  layout "admin"
  before_action :set_recipe, only: [ :destroy, :show ]

  def index
    @recipes = Recipe.all
  end

  def show
  end

  def new
  end

  def create
    @recipe = current_user.recipes.create(recipe_params)
    if @recipe.save
      respond_to do |format|
        format.html { redirect_to recipes_url, notice: "Recipe added!" }
      end
    else
    respond_to do |format|
        format.html { redirect_to recipes_url, alert: @recipe.errors.full_messages[0] }
      end
    end
  end

  def destroy
    if @recipe.destroy
      respond_to do |format|
        format.html { redirect_to recipes_url, notice: "Recipe deleted!" }
      end
    else
      respond_to do |format|
        format.html { redirect_to recipes_url, alert: @recipe.errors.full_messages[0] }
      end
    end
  end

  private
  def recipe_params
    params.require(:recipe).permit(:name, :description, :preparation_duration, :cooking_duration, :public)
  end
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/inventory_foods_helper.rb
module InventoryFoodsHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shopping_list_helper.rb
module ShoppingListHelper
end

app/views/foods/index.html.erb
<div class="flex flex-col w-full text-gray-200">
  <div class="flex items-center px-10 <%=@foods.size > 0 ? "justify-end" : "justify-between" %> my-4">
    <% if @foods.size < 1 %>
      <p class="font-bold text-xl text-yellow-300">No food items added yet!</p>
    <%end%>
    <%= button_to "Add Food", new_food_path, method: :get, data: {turbo: true, turbo_frame: :modal},
    class:"bg-blue-500 p-2 rounded-md cursor-pointer" %>
  </div>
  <div class="w-full">
    <div class="flex justify-center items-center bg-gray-600 rounded-md p-2 w-full md:w-[80%] mx-auto overflow-x-auto">
      <table class="rounded-md text-xs p-4 sm:text-sm md:text-base w-full">
        <thead>
          <tr class="text-left capitalize md:uppercase border-b border-blue-500">
            <th class="sm:px-4 sm:py-3">Food</th>
            <th class="sm:px-4 sm:py-3">Measurement Unit</th>
            <th class="sm:px-4 sm:py-3">Unit Price</th>
            <th class="sm:px-4 sm:py-3">Actions</th>
          </tr>
        </thead>
        <tbody>
          <%@foods.each do |food|%>
            <tr class="my-1 sm:my-0">
              <td class="sm:px-4 sm:py-3"><%= food.name %></td>
              <td class="sm:px-4 sm:py-3"><%= food.measurement_unit %></td>
              <td class="sm:px-4 sm:py-3">$<%= food.price %></td>
              <td class="sm:px-4 sm:py-3">
                <%= button_to "Delete", food_path(food), method: :delete, class:"bg-red-500 p-1 my-2 md:px-4 md:my-0 cursor-pointer rounded-md"%>
              </td>
            </tr>
          <%end%>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/foods/new.html.erb
<%= turbo_frame_tag :modal do %>
  <div class="fixed inset-0 bg-black/80"></div>
  <div class="fixed inset-0 bg-transparent flex items-center justify-center">
    <div class="relative flex items-center justify-center w-96 z-50 bg-gray-400 p-4 rounded-md">
      <%= form_with model: Food.new, data: {turbo: false} do |f|%>
        <div class="mb-4">
          <%= f.label :name, class:"block mb-2 text-gray-950" %>
          <%= f.text_field :name,
            autofocus: false,
            autocomplete: "name",
            class: "w-full px-3 py-2 border text-gray-100 rounded-lg bg-gray-600 outline-none"
          %>
        </div>
        <div class="mb-4">
          <%= f.label :measurement_unit, class:"block mb-2 text-gray-950" %>
          <%= f.text_field :measurement_unit,
            autofocus: true,
            autocomplete: "measurement_unit",
            class: "w-full px-3 py-2 border text-gray-100 rounded-lg bg-gray-600 outline-none"
          %>
        </div>
        <div class="mb-4">
          <%= f.label :price, class:"block mb-2 text-gray-950" %>
          <%= f.number_field :price,
            autofocus: true,
            autocomplete: "price",
            class: "w-full px-3 py-2 border text-gray-100 rounded-lg bg-gray-600 outline-none"
          %>
        </div>
        <div class="flex items-center justify-center mb-2 my-2">
          <%= f.submit "Create",
            class:"bg-orange-500 hover:bg-orange-600 text-gray-200 font-semibold lg:text-xl p-2 rounded-md cursor-pointer w-[70%]",
            data: {turbo_frame: "_top"}
            %>
        </div>
        <div class="absolute top-2 right-2">
          <%=link_to foods_path do %>
            <%= inline_svg_tag("close.svg", class:"text-gray-800 size-8")%>
          <%end%>
        </div>
      <%end%>
    </div>
  <div>
<%end%>

app/views/recipes/index.html.erb
<div class="flex flex-col w-full text-xs md:text-base text-gray-200">
  <div class="flex items-center px-10 <%= @recipes.size > 0 ? "justify-end" : "justify-between" %> my-4">
    <% if @recipes.size < 1 %>
      <p class="font-bold text-xl text-yellow-300">No recipes added yet!</p>
    <%end%>
    <%= button_to "Add Recipe", new_recipe_path, method: :get, data: {turbo: true, turbo_frame: :modal},
    class:"bg-blue-500 p-2 rounded-md cursor-pointer" %>
  </div>
  <div class="flex flex-col justify-center items-center">
    <% @recipes.each do |recipe|%>
      <div class="flex gap-10 border border-gray-400 shadow-md w-[90%] my-4 mx-auto p-5 rounded-md">
        <div class="flex flex-col items-center justify-center gap-5">
          <p class="font-semibold text-sm md:text-xl text-blue-300 underline">
            <%=link_to recipe.name, recipe_path(recipe) %>
          </p>
          <%=button_to "REMOVE", recipe_path(recipe), method: :delete, class:"text-blue-400 uppercase cursor-pointer"%>
        </div>
        <div class="">
          <p class="text-xs md:text-base">
            <%= recipe.description%>
          <p>
        </div>
      </div>
    <%end%>
  </div>
</div>

app/views/recipes/new.html.erb
<%= turbo_frame_tag :modal do %>
  <div class="fixed inset-0 bg-black/80"></div>
  <div class="fixed inset-0 bg-transparent flex items-center justify-center">
    <div class="relative flex items-center justify-center w-96 z-50 bg-gray-400 p-4 rounded-md">
      <%= form_with model: Recipe.new, data: {turbo: false} do |f|%>
        <div class="mb-4">
          <%= f.label :name, class:"block mb-2 text-gray-950" %>
          <%= f.text_field :name,
            autofocus: false,
            autocomplete: "name",
            class: "w-full px-3 py-2 border text-gray-100 rounded-lg bg-gray-600 outline-none"
          %>
        </div>
        <div class="mb-4">
          <%= f.label :description, class:"block mb-2 text-gray-950" %>
          <%= f.text_field :description,
            autofocus: true,
            autocomplete: "description",
            class: "w-full px-3 py-2 border text-gray-100 rounded-lg bg-gray-600 outline-none"
          %>
        </div>
        <div class="mb-4">
          <%= f.label :preparation_duration,"Preparation Time (HH:MM)", class:"block mb-2 text-gray-950" %>
          <%= f.text_field :preparation_duration,
            value: f.object.preparation_duration,
            autofocus: true,
            placeholder:"00:45",
            autocomplete: "preparation_time",
            class: "w-full px-3 py-2 border text-gray-100 rounded-lg bg-gray-600 outline-none"
          %>
        </div>
        <div class="mb-4">
          <%= f.label :cooking_duration, "Cooking Time (HH:MM)", class:"block mb-2 text-gray-950" %>
          <%= f.text_field :cooking_duration,
            value: f.object.cooking_duration,
            autofocus: true,
            placeholder:"01:30",
            autocomplete: "cooking_time",
            class: "w-full px-3 py-2 border text-gray-100 rounded-lg bg-gray-600 outline-none"
          %>
        </div>
        <div class="flex items-center justify-start gap-4 mb-4">
          <%= f.label :public, class:"block mb-2 text-gray-950" %>
          <%= f.check_box :public,
            autofocus: true,
            autocomplete: "public",
            class: "p-4 size-4 border text-gray-100 mb-2 bg-gray-600 outline-none"
          %>
        </div>
        <div class="flex items-center justify-center mb-2 my-2">
          <%= f.submit "Create",
            class:"bg-orange-500 hover:bg-orange-600 text-gray-200 font-semibold lg:text-xl p-2 rounded-md cursor-pointer w-[70%]",
            data: {turbo_frame: "_top"}
            %>
        </div>
        <div class="absolute top-2 right-2">
          <%=link_to recipes_path do %>
            <%= inline_svg_tag("close.svg", class:"text-gray-800 size-8")%>
          <%end%>
        </div>
      <%end%>
    </div>
  <div>
<%end%>

app/views/recipes/show.html.erb
<div class="flex flex-col text-xs md:text-base items-center mt-10 px-5 text-gray-200 w-full">
  <p class="font-semibold text-xl">
    <%=@recipe.name%>
  </p>
  <div class="flex justify-between w-full md:w-[80%] mx-auto mb-5 mt-10">
    <div class="flex flex-col gap-4">
      <p>Preparation duration: <%= @recipe.preparation_duration%> (HH:MM)</p>
      <p>Cooking duration: <%=@recipe.cooking_duration%> (HH:MM)</p>
      <p>Steps go here...</p>
    </div>
    <div class="">
      <p>Public</p>
    </div>
  </div>
  <div class="flex justify-between gap-5 items-center w-full md:w-[80%]">
      <%= link_to "Generate shopping list", new_shopping_list_path(recipe_id: @recipe.id), data:{turbo: true, turbo_frame: :modal}, class:"cursor-pointer bg-blue-500 rounded-md text-xs md:text-base p-1 hover:bg-blue-400" %>
      <%= link_to "Add ingredient", new_recipe_recipe_food_path(@recipe), class:"cursor-pointer bg-blue-500 rounded-md p-1 hover:bg-blue-400 text-xs md:text-base" %>
  </div>
  <div class="border-b-2 border-gray-950 my-2 w-full md:w-[80%]"></div>
  <div class="w-full md:w-[80%] bg-gray-600 rounded-md px-2">
    <table class="w-full">
      <thead>
        <tr class="text-left capitalize md:uppercase border-b border-blue-500">
          <th class="sm:px-4 sm:py-3">Food</th>
          <th class="sm:px-4 sm:py-3">Quantity</th>
          <th class="sm:px-4 sm:py-3">Value</th>
          <th class="sm:px-4 sm:py-3">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @recipe.recipe_foods.each do |recipe_food| %>
          <tr>
            <td class="sm:px-4 sm:py-3"><%=recipe_food.food.name %></td>
            <td class="sm:px-4 sm:py-3"><%=recipe_food.quantity %></td>
            <td class="sm:px-4 sm:py-3"><%=recipe_food.quantity*recipe_food.food.price%></td>
            <td class="flex gap-5 capitalize sm:px-4 sm:py-3">
              <%=link_to "Modify", edit_recipe_recipe_food_path(@recipe), class:"text-blue-400 underline cursor-pointer"%>
              <%= button_to "Remove", recipe_recipe_food_path(@recipe, recipe_food), method: :delete, class:"text-blue-400 underline cursor-pointer"%>
            </td>
      
          <tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>